
import { LayoutDashboard, BookOpen, Users, History, Settings } from 'lucide-react';
import { LoanStatus, Role } from './types';
import type { Book, Loan, User, NavItem } from './types';



export const NAV_ITEMS: NavItem[] = [
  { label: 'Tableau de bord', path: '/', icon: LayoutDashboard },
  { label: 'Catalogue', path: '/catalog', icon: BookOpen },
  { label: 'Gestion Livres', path: '/admin/books', icon: Settings }, // <-- NOUVEAU
  { label: 'Emprunts', path: '/loans', icon: History },
  { label: 'Membres', path: '/members', icon: Users },
];

export const MOCK_USER: User = {
  id: 'u1',
  name: 'cheb mami',
  email: 'mami.admin@bibliotech.com',
  role: Role.ADMIN,
  avatarUrl: 'https://tse3.mm.bing.net/th/id/OIP.pkA4ZlQPqXn7PsslQHzIbQHaHa?rs=1&pid=ImgDetMain&o=7&rm=3',
};

export const MOCK_BOOKS: Book[] = [
  {
    id: 'b1',
    isbn: '978-0123456789',
    title: 'Les Misérables',
    author: 'Victor Hugo',
    publisher: 'Gallimard',
    year: 1862,
    genre: 'Roman',
    summary: "L'histoire de Jean Valjean, un ancien forçat...",
    coverUrl: 'https://m.media-amazon.com/images/I/613R0HknEEL._SL1413_.jpg',
    availableCopies: 2,
    totalCopies: 5,
  },
  {
    id: 'b2',
    isbn: '978-0987654321',
    title: '1984',
    author: 'George Orwell',
    publisher: 'Folio',
    year: 1949,
    genre: 'Science-fiction',
    summary: 'Une dystopie sur un régime totalitaire...',
    coverUrl: 'https://th.bing.com/th/id/R.f1b4e91832c4615a43955f2d0f5d1795?rik=MW2%2bzNXYZBR9hw&riu=http%3a%2f%2fwww.bookerworm.com%2fimages%2f1984.jpg&ehk=l8MIFhiWt69hsoMix5qeAYOzlObLECDEUWhhsiywKk4%3d&risl=&pid=ImgRaw&r=0',
    availableCopies: 0,
    totalCopies: 3,
  },
  {
    id: 'b3',
    isbn: '978-1122334455',
    title: 'Le Petit Prince',
    author: 'Antoine de Saint-Exupéry',
    publisher: 'Gallimard',
    year: 1943,
    genre: 'Conte',
    summary: 'Un pilote échoué dans le désert rencontre un petit prince...',
    coverUrl: 'https://cdn2.penguin.com.au/covers/original/9781784874186.jpg',
    availableCopies: 10,
    totalCopies: 12,
  },
  {
    id: 'b4',
    isbn: '978-5566778899',
    title: 'L\'Étranger',
    author: 'Albert Camus',
    publisher: 'Gallimard',
    year: 1942,
    genre: 'Roman',
    summary: 'Meursault, un homme indifférent, commet un meurtre...',
    coverUrl: 'https://th.bing.com/th/id/R.f1d24fc4f31117c5870a8c1ef9e7fa98?rik=7S58sEO097EOQg&pid=ImgRaw&r=0',
    availableCopies: 4,
    totalCopies: 6,
  },
  {
    id: 'b5',
    isbn: '978-9988776655',
    title: 'Dune',
    author: 'Frank Herbert',
    publisher: 'Pocket',
    year: 1965,
    genre: 'Science-fiction',
    summary: 'Paul Atreides sur la planète désertique Arrakis...',
    coverUrl: 'https://tse4.mm.bing.net/th/id/OIP.k2_uScezkUmDh-cjxSbAkQAAAA?rs=1&pid=ImgDetMain&o=7&rm=3',
    availableCopies: 1,
    totalCopies: 4,
  },
  {
    id: 'b6',
    isbn: '978-2253004226',
    title: 'Germinal',
    author: 'Émile Zola',
    publisher: 'Le Livre de Poche',
    year: 1885,
    genre: 'Roman',
    summary: 'La révolte des mineurs du Nord...',
    coverUrl: 'https://th.bing.com/th/id/R.96208eda0f85a2b8de269c8430645476?rik=Q7SWY7XqhO7cqQ&pid=ImgRaw&r=0',
    availableCopies: 3,
    totalCopies: 5,
  },
  {
    id: 'b7',
    isbn: '978-2070368228',
    title: 'Fahrenheit 451',
    author: 'Ray Bradbury',
    publisher: 'Folio SF',
    year: 1953,
    genre: 'Science-fiction',
    summary: 'Un futur où les livres sont brûlés...',
    coverUrl: 'https://librairielechatbleu.com/wp-content/uploads/fahrenheit-451-5731.jpg',
    availableCopies: 5,
    totalCopies: 8,
  },
  {
    id: 'b8',
    isbn: '978-2070416165',
    title: 'Le Vieil Homme et la Mer',
    author: 'Ernest Hemingway',
    publisher: 'Gallimard',
    year: 1952,
    genre: 'Roman',
    summary: 'Le combat d\'un vieux pêcheur contre un marlin géant...',
    coverUrl: 'https://th.bing.com/th/id/R.f17b9a7342277b1f5fb7986e114d89dc?rik=Glb%2bxt2j4opMtg&pid=ImgRaw&r=0',
    availableCopies: 6,
    totalCopies: 6,
  },
  {
    id: 'b9',
    isbn: '978-2253002864',
    title: 'Vingt mille lieues sous les mers',
    author: 'Jules Verne',
    publisher: 'Le Livre de Poche',
    year: 1870,
    genre: 'Aventure',
    summary: 'Le capitaine Nemo et son sous-marin, le Nautilus...',
    coverUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Houghton_FC8_V5946_869ve_-_Verne%2C_frontispiece.jpg/960px-Houghton_FC8_V5946_869ve_-_Verne%2C_frontispiece.jpg',
    availableCopies: 2,
    totalCopies: 4,
  },
  {
    id: 'b10',
    isbn: '978-2070360024',
    title: 'La Peste',
    author: 'Albert Camus',
    publisher: 'Gallimard',
    year: 1947,
    genre: 'Roman',
    summary: 'Chronique d\'une épidémie de peste à Oran...',
    coverUrl: 'https://tse3.mm.bing.net/th/id/OIP.hB9aXo4fGJuYtW6efums4wHaL3?rs=1&pid=ImgDetMain&o=7&rm=3',
    availableCopies: 1,
    totalCopies: 3,
  },
  {
    id: 'b11',
    isbn: '978-2081219228',
    title: 'L\'Odyssée',
    author: 'Homère',
    publisher: 'Flammarion',
    year: -800,
    genre: 'Épopée',
    summary: 'Le retour d\'Ulysse à Ithaque...',
    coverUrl: 'https://editions.flammarion.com/media/cache/couverture_medium/flammarion_img/Couvertures/9782080268839.jpg',
    availableCopies: 8,
    totalCopies: 10,
  },
  {
    id: 'b12',
    isbn: '978-2070375165',
    title: 'Le Meilleur des mondes',
    author: 'Aldous Huxley',
    publisher: 'Folio',
    year: 1932,
    genre: 'Science-fiction',
    summary: 'Une société future conditionnée et contrôlée...',
    coverUrl: 'https://m.media-amazon.com/images/I/71iZzLwuZML._SL1311_.jpg',
    availableCopies: 3,
    totalCopies: 5,
  },
];

export const MOCK_LOANS: Loan[] = [
  {
    id: 'l1',
    bookId: 'b2',
    userId: 'u2',
    borrowDate: '2023-10-01',
    dueDate: '2023-10-15',
    status: LoanStatus.OVERDUE,
    bookTitle: '1984',
    userName: 'Jean Dupont',
  },
  {
    id: 'l2',
    bookId: 'b1',
    userId: 'u3',
    borrowDate: '2023-10-20',
    dueDate: '2023-11-03',
    status: LoanStatus.ACTIVE,
    bookTitle: 'Les Misérables',
    userName: 'Marie Curie',
  },
  {
    id: 'l3',
    bookId: 'b3',
    userId: 'u4',
    borrowDate: '2023-10-22',
    dueDate: '2023-11-05',
    status: LoanStatus.ACTIVE,
    bookTitle: 'Le Petit Prince',
    userName: 'Albert Einstein',
  },
];

export const DASHBOARD_STATS = [
  { name: 'Jan', loans: 400, returns: 350 },
  { name: 'Fév', loans: 300, returns: 280 },
  { name: 'Mar', loans: 550, returns: 500 },
  { name: 'Avr', loans: 450, returns: 430 },
  { name: 'Mai', loans: 600, returns: 580 },
  { name: 'Juin', loans: 700, returns: 650 },
];

export const GENRE_DISTRIBUTION = [
  { name: 'Roman', value: 45 },
  { name: 'Science-fiction', value: 25 },
  { name: 'Histoire', value: 15 },
  { name: 'Biographie', value: 10 },
  { name: 'Autre', value: 5 },
];